# Generated by Django 3.1.2 on 2020-11-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('재학', '재학'), ('휴학', '휴학'), ('졸업', '졸업'), ('자퇴', '자퇴')], max_length=5)),
            ],
        ),
    ]
