# Generated by Django 3.1.2 on 2020-11-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('equip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='RentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_pic', models.ImageField(upload_to='equip_pic/%Y/%m/%d/')),
                ('equip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_equip_id', to='equipments.equipment')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_students', to='students.student')),
            ],
        ),
    ]
