# Generated by Django 3.1.2 on 2020-11-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_pic', models.ImageField(upload_to='equip_pic/%Y/%m/%d/')),
                ('return_date', models.DateTimeField(default=None)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentemail', to='students.student')),
                ('equip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_equip_id', to='equipments.equipment')),
                ('equip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_equip_type', to='equipments.equipment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_name', to='students.student')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_phone_number', to='students.student')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_students', to='students.student')),
            ],
        ),
    ]
