# Generated by Django 3.1.2 on 2020-11-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.CharField(max_length=255)),
                ('equip_type', models.CharField(blank=True, choices=[('laptop', '노트북'), ('tablet', '태블릿'), ('sensor', '센서')], max_length=20, null=True)),
                ('rent_status', models.BooleanField(default=False)),
            ],
        ),
    ]
