# Generated by Django 3.1.2 on 2020-11-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equip_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
